project-includes = ["src", "tests"]
project-excludes = [
  "**/__pycache__",
  ".venv",
]
search-path = ["src"]
site-package-path = [".venv/lib/python3.9/site-packages"]
python-interpreter-path = ".venv/bin/python"
